---
name: Aaron Conway
position: "RBC Chair in Cardiovascular Nursing Research"
address: "Peter Munk Cardiac Centre, UHN and University of Toronto"
phone: +1 (416) 946-7112
www: aaronconway.info
email: "aaron.conway@utoronto.ca"
twitter: aw_conway
github: awconway
linkedin: aaron-conway-toronto
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
params:
  orcid.id: "0000-0002-9583-8636"
  years.since: 2010
  spacer: ', '
  journal.only: "No"
  order: "dyear"
  max.authors: 3
  style: "APA"
  bullets: 'numbers'
  extra.order: 'None'
  flag.OA: FALSE
  bold.author: FALSE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(cvR)
library(shiny)
library(scholar)
library(rorcid)
library(kableExtra)
library(ggplot2)
x  <- "dc7ea3ae-38fd-4188-8bd1-1db4215ea139"
Sys.setenv(ORCID_TOKEN=x, orcid_email="aaron.conway@utoronto.ca")
```

  
# Education

```{r}
edu <- rorcid::orcid_educations(params$orcid.id)
edu <- edu$`0000-0002-9583-8636`$`education-summary` %>% 
  janitor::clean_names() %>% 
  mutate(end_date = tidyr::replace_na(`end_date_year_value`, "Current")) %>%
  mutate(timeframe = glue::glue("{start_date_year_value} - {end_date}")) %>% 
    mutate(location = glue::glue("{organization_address_city}, {organization_address_country}")) %>% 
  select(role_title, organization_name, location, timeframe)

detailed_entries(edu, what = role_title, with = organization_name, when = timeframe, where = location)
```

# Employment

```{r}
employ <- rorcid::orcid_employments(params$orcid.id)
employ <- employ$`0000-0002-9583-8636`$`employment-summary` %>% 
  janitor::clean_names() %>% 
  mutate(end_date = tidyr::replace_na(`end_date_year_value`, "Current")) %>%
  mutate(timeframe = glue::glue("{start_date_year_value} - {end_date}")) %>% 
    mutate(location = glue::glue("{organization_address_city}, {organization_address_country}")) %>% 
  select(role_title, organization_name, location, timeframe)

detailed_entries(employ, what = role_title, with = organization_name, when = timeframe, where = location)
```

<!-- orcid api version 3.0 change to rorcid function -->

```{r}
ocom <- function(l) Filter(Negate(is.null), l)
ocom2 <- function(l) Filter(function(l) !is.null(l) && length(l) > 0, l)

orcid_base <- function() "https://pub.orcid.org/v3.0_rc1"

ojson <- "application/vnd.orcid+json; qs=4"

orc_GET <- function(url, args = list(), ctype = ojson, ...) {
  cli <- crul::HttpClient$new(
    url = url,
    opts = list(...),
    headers = list(
      Accept = ctype,
      `User-Agent` = orcid_ua(),
      'X-USER-AGENT' = orcid_ua(),
      Authorization = orcid_auth()
    )
  )
  res <- cli$get(query = args)
  errs(res)
  res$parse("UTF-8") 
}

check_key <- function() {
  x <- Sys.getenv("ORCID_TOKEN", "")
  if (x == "") {
    x <- getOption("orcid_token", "")
  }
  if (x == "") NULL else x
}

orcid_ua <- function() {
  versions <- c(
    paste0("r-curl/", utils::packageVersion("curl")),
    paste0("crul/", utils::packageVersion("crul")),
    sprintf("rOpenSci(rorcid/%s)", utils::packageVersion("rorcid"))
  )
  paste0(versions, collapse = " ")
}

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) == 0) y else x
}

errs <- function(x) {
  if (x$status_code > 201) {
    xx <- jsonlite::fromJSON(x$parse("UTF-8"))
    if (any(c("error-code", "errorCode") %in% names(xx))) {
      # match by status code
      fun <- fauxpas::find_error_class(x$status_code)$new()
      fun$mssg <- xx$`developer-message` %||% xx$developerMessage
      fun$do_verbose(x)
    } else {
      # if no error message in response, just general stop
      fauxpas::http(x)
    }
  }
}

fuzzydoi <- function(x, fuzzy = FALSE) {
  if (fuzzy) {
    x
  } else {
    sprintf("digital-object-ids:\"%s\"", x)
  }
}

orc_parse <- function(x){
  out <- jsonlite::fromJSON(x, TRUE, flatten = TRUE)
  df <- tibble::as_data_frame(out$result)
  # names(df) <- gsub("orcid-profile\\.|orcid-profile\\.orcid-bio\\.", "", names(df))
  attr(df, "found") <- out$`num-found`
  return(df)
}

# From the plyr package
failwith <- function(default = NULL, f, quiet = FALSE) {
  f <- match.fun(f)
  function(...) try_default(f(...), default, quiet = quiet)
}

# From the plyr package
try_default <- function(expr, default, quiet = FALSE) {
  result <- default
  if (quiet) {
    tryCatch(result <- expr, error = function(e) {
    })
  }
  else {
    try(result <- expr)
  }
  result
}

pluck <- function(x, name, type) {
  if (missing(type)) {
    lapply(x, "[[", name)
  } else {
    vapply(x, "[[", name, FUN.VALUE = type)
  }
}

pop <- function(x, name) x[ !names(x) %in% name ]

orcid_prof_helper <- function(x, path, ctype = ojson, ...) {
  url2 <- file.path(orcid_base(), x, path)
  out <- orc_GET(url2, ctype = ctype, ...)
  switch_parser(ctype, out)
}

switch_parser <- function(ctype, x) {
  switch(
    ctype,
    `application/vnd.orcid+xml; qs=5` = px(x), 
    `application/orcid+xml; qs=3` = px(x), 
    `application/xml` = px(x), 
    `application/vnd.orcid+json; qs=4` = pj(x), 
    `application/orcid+json; qs=2` = pj(x), 
    `application/json` = pj(x), 
    `application/vnd.citationstyles.csl+json` = pj(x),
    stop("no parser found for ", ctype)
  )
}

pj <- function(z) jsonlite::fromJSON(z, flatten = TRUE)
px <- function(z) xml2::read_xml(z)

orcid_putcode_helper <- function(path, orcid, put_code, format, ...) {
  if (!is.null(put_code)) {
    if (length(orcid) > 1) {
      stop("if 'put_code' is given, 'orcid' must be length 1")
    }
  }
  pth <- if (is.null(put_code)) path else file.path(path, put_code)
  if (length(pth) > 1) {
    stats::setNames(
      Map(function(z) orcid_prof_helper(orcid, z, ctype = format), pth), 
      put_code)
  } else {
    nmd <- if (!is.null(put_code)) put_code else orcid
    stats::setNames(
      lapply(orcid, orcid_prof_helper, path = pth, ctype = format, ...), nmd)
  }
}

as_dt <- function(x, tibble = TRUE) {
  z <- data.table::setDF(
    data.table::rbindlist(x, use.names = TRUE, fill = TRUE)
  )
  if (tibble) z <- tibble::as_tibble(z)
  return(z)
}

```

# Awards

```{r}
orcid_distinction <- function(orcid, put_code = NULL, 
                          format = "application/json", summary = FALSE, ...) {
  
  pth <- if (!summary) {
    if (is.null(put_code)) "distinctions" else "distinction"
  } else {
    if (is.null(put_code)) {
      stop("if summary == TRUE, must give 1 or more put_code")
    }
    "distinction/summary"
  }
  orcid_putcode_helper(pth, orcid, put_code, format, ...)
}

distinctions  <- orcid_distinction(params$orcid.id)
distinctions <- distinctions$`0000-0002-9583-8636`$`affiliation-group`$summaries 
distinctions <- tibble(
  organization = purrr::map_chr(distinctions, "distinction-summary.organization.name"),
  title = purrr::map_chr(distinctions, "distinction-summary.role-title"),
  time = purrr::map_chr(distinctions, "distinction-summary.start-date.year.value"))

detailed_entries(distinctions, what = title, with = organization, when = time)
```

# Service

```{r}
orcid_service <- function(orcid, put_code = NULL, 
                          format = "application/json", summary = FALSE, ...) {
  
  pth <- if (!summary) {
    if (is.null(put_code)) "services" else "service"
  } else {
    if (is.null(put_code)) {
      stop("if summary == TRUE, must give 1 or more put_code")
    }
    "service/summary"
  }
  orcid_putcode_helper(pth, orcid, put_code, format, ...)
}

service  <- orcid_service(params$orcid.id)

currentFunction <- function(x){
  if(!is.null(service$`0000-0002-9583-8636`$`affiliation-group`$summaries[[x]]$`service-summary.end-date`)){
     "Current"
  } else {service$`0000-0002-9583-8636`$`affiliation-group`$summaries[[x]]$`service-summary.end-date.year.value`}
}

end_year <- vapply(seq(1, length(service$`0000-0002-9583-8636`$`affiliation-group`$summaries), by = 1), currentFunction, "")


service  <- service$`0000-0002-9583-8636`$`affiliation-group`$summaries
service <- tibble(
  organization = purrr::map_chr(service, "service-summary.organization.name"),
  title = purrr::map_chr(service, "service-summary.role-title"),
  start = purrr::map_chr(service, "service-summary.start-date.year.value"))

service$time <- glue::glue("{service$start} - {end_year}") 

detailed_entries(service, what = title, with = organization, when = glue::glue("{start} - {end_year}"))
```



<!-- No invited positions to list -->
```{r}
orcid_invited_position <- function(orcid, put_code = NULL, 
                          format = "application/json", summary = FALSE, ...) {
  
  pth <- if (!summary) {
    if (is.null(put_code)) "invited-positions" else "invited-position"
  } else {
    if (is.null(put_code)) {
      stop("if summary == TRUE, must give 1 or more put_code")
    }
    "invited-position/summary"
  }
  orcid_putcode_helper(pth, orcid, put_code, format, ...)
}

invited_position  <- orcid_invited_position(params$orcid.id)
invited_position <- invited_position$`0000-0002-9583-8636`$`affiliation-group`$summaries 

invited_position <- tibble(
  organization = purrr::map_chr(invited_position, "invited-position-summary.organization.name"),
  title = purrr::map_chr(invited_position, "invited-position-summary.role-title"),
  time = purrr::map_chr(invited_position, "invited-position-summary.start-date.year.value"))
```

# Memberships

```{r}
orcid_membership <- function(orcid, put_code = NULL, 
                          format = "application/json", summary = FALSE, ...) {
  
  pth <- if (!summary) {
    if (is.null(put_code)) "memberships" else "membership"
  } else {
    if (is.null(put_code)) {
      stop("if summary == TRUE, must give 1 or more put_code")
    }
    "membership/summary"
  }
  orcid_putcode_helper(pth, orcid, put_code, format, ...)
}

membership  <- orcid_membership(params$orcid.id)

currentFunction <- function(x){
  if(!is.null(membership$`0000-0002-9583-8636`$`affiliation-group`$summaries[[x]]$`membership-summary.end-date`)){
     "Current"
  } else {membership$`0000-0002-9583-8636`$`affiliation-group`$summaries[[x]]$`membership-summary.end-date.year.value`}
}

end_year <- vapply(seq(1, length(membership$`0000-0002-9583-8636`$`affiliation-group`$summaries), by = 1), currentFunction, "")

membership <- membership$`0000-0002-9583-8636`$`affiliation-group`$summaries 

membership <- tibble(
  organization = purrr::map_chr(membership, "membership-summary.organization.name"),
  title = purrr::map_chr(membership, "membership-summary.role-title"),
  start = purrr::map_chr(membership, "membership-summary.start-date.year.value"))

membership$time <- glue::glue("{membership$start} - {end_year}") 

detailed_entries(membership, what = title, when = time, with = organization)
```



# Funding


```{r}
funding <- rorcid::orcid_fundings(params$orcid.id)
pcodes <- vapply(funding[[1]]$group$`funding-summary`, "[[", 1, "put-code")
out <- lapply(pcodes, function(z) orcid_fundings(params$orcid.id, put_code=z))
amount <- vapply(out, function(w) w[[1]]$amount$value, "")
amount  <- paste("$", amount, sep = "")
funding <- funding$`0000-0002-9583-8636`$group$`funding-summary` 
funding <- tibble(
  type = purrr::map_chr(funding, "type"),
  funder = purrr::map_chr(funding, "organization.name"),
  title = purrr::map_chr(funding, "title.title.value"),
  start = purrr::map_chr(funding, "start-date.year.value"),
  end = purrr::map_chr(funding, "end-date.year.value")) %>% 
  mutate(timeframe = glue::glue("{start} - {end}")) %>% 
  select(type, funder, title, timeframe) 
funding$type <- stringr::str_replace_all(funding$type, "SALARY_AWARD", "SALARY AWARD")
  funding <- funding %>% 
  mutate(Amount = amount)
  detailed_entries(funding, what = type, with = funder, when = timeframe, where = Amount, why = title)
```

# Open Source Software

```{r}
software <- tribble(~package, ~description, ~year,
                    "spiritR", "A workflow to enable direct upload of a clinical trial protocol to clinicaltrials.gov
", 2019)
detailed_entries(software, what = description, with = package, when = year)
```

# Publications

```{r}
results <- my.orcid(params$orcid.id) # single
```


```{r}
papers  <-  my.filter(results, max.authors=params$max.authors, order=params$order,
                   journal.only=params$journal.only, years.since=params$years.since,
                   spacer=params$spacer, bold.author = params$bold.author)
```

```{r list.papers, results='asis'}
print_papers(papers)
```



# Peer reviews
```{r}
reviews <- rorcid::orcid_peer_reviews(params$orcid.id)
reviews <- reviews$`0000-0002-9583-8636`$group$`peer-review-summary`
get_title_from_issn <- function(issn) {
  tryCatch(issn_title[[issn]], error = function(e) {rcrossref::cr_journals(issn)$data$title})
}

issnfunction <- function(x){
  issn <- stringr::str_remove(reviews[[x]]$`review-group-id`[1], "issn:")
if(issn == "1532-8473") {
  "Journal of Peri-Anesthesia Nursing"
} else if(issn == "1651-2219"){
  "Annals of Medicine"
}  else if(issn == "publons:Wiley"){
  "Wiley journal not otherwise classified"
  }   else if(issn == "1469-493X"){
  "Cochrane Database of Systematic Reviews"
  }   else if(issn == "1552-3799"){
  "Clinical Nursing Research"
  } else if(issn == "publons:Elsevier"){
  "Elsevier journal not otherwise classified"
  } else(get_title_from_issn(issn))
}

journalsReviewed <- vapply(seq(1,length(reviews), by = 1), issnfunction, "")  
  

numberReviewsFunction <- function(x){
  length(reviews[[x]]$`review-group-id`)
}

numberReviewed <- purrr::map_dbl(seq(1,length(reviews), by = 1), numberReviewsFunction)  
reviewdf <- tibble(journalsReviewed, numberReviewed)
reviewdf$journalsReviewed <- recode(reviewdf$journalsReviewed, "Collegian Journal of the Royal College of Nursing Australia" = "Collegian")
totalreviews <- sum(reviewdf$numberReviewed)
```

```{r}
reviewdf %>% 
  arrange(desc(numberReviewed)) %>% 
detailed_entries(with = journalsReviewed, when = numberReviewed)
```

