---
name: Aaron Conway
position: "Chair in Cardiovascular Nursing"
phone: +1 (416) 340-4654
email: "aaron.conway@utoronto.ca"
twitter: aw_conway
github: awconway
profilepic: bio-pic-small.png
www: aaronconway.info
linkedin: aaron-conway-toronto
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: ""
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
library(scholar)
library(rorcid)
knitr::opts_chunk$set(echo = FALSE)
Sys.getenv("ORCID_TOKEN")
```

# Education
```{r }
edu <- rorcid::orcid_educations("0000-0002-9583-8636")
edu$`0000-0002-9583-8636`$`education-summary` %>% 
  mutate(`end-date.year.value` = replace_na(`end-date.year.value`, "2019")) %>% 
  detailed_entries(
    what = 'title.title.value')
```


# Publications
```{r publications}
scholar::get_publications("2hpmnr8AAAAJ") %>%
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal
  )
```